config/routes.rb
SohoPropAssignment::Application.routes.draw do

  root 'pages#home'
  get 'users' => 'users#index'
  post 'users/import' => 'users#import_csv_data', as: :import_csv_data
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :date, :number, :description, presence: true

  class << self
    def import_data(csv_content)
      failed_tries = []
      csv_content.each do |row|
        user = User.new(row.to_hash)
        failed_tries << row unless user.save
      end
      failed_tries.count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home;end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require 'csv'
  CSV_NAME = 'soho-coding-test-file.csv'

  before_action :check_file, only: :import_csv_data
  before_action :destroy_existing_list, only: :import_csv_data

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def import_csv_data
    read_file
    parse_csv
    import_data
    if @failed_count > 0
      flash[:error] = "#{view_context.pluralize(@failed_count, 'user')} dropped due to missing data"
    else
      flash[:success] = "All users imported!"
    end
    redirect_to users_path
  end

  private

  def check_file
    if params[:file] && params[:file].original_filename != CSV_NAME
      flash[:error] = "File not recognized. Pls upload Soho Test CSV file"
      redirect_to :back
    end
  end

  def read_file
    @csv_file = File.read(params[:file].path)
  end

  def parse_csv
    @csv_content = CSV.parse(@csv_file, :headers => true)
  end

  def import_data
    @failed_count = User.import_data(@csv_content)
  end

  def destroy_existing_list
    User.destroy_all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SohoPropAssignment</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, value| %>
  	<div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%= yield %>
</body>
</html>

app/views/pages/home.html.slim
.container.pull-lower
	.row
		.column-in-center
			h1 CSV Parser
.container.pull-lower
	.row
		.column-in-center
			= form_tag import_csv_data_path, multipart: true, method: :post do
				= file_field_tag :file, :id => 'upload-file-button'
				= submit_tag "Import", :class => 'btn btn-primary', :id => 'import-file-button', disabled: true
	.row.pull-lower
		.column-in-center
			- if User.all.present?
				= link_to 'View List', users_path, :class => 'btn btn-primary'

app/views/users/index.html.slim
.container.pull-lower
	.row
		.col-md-6.col-sm-6.col-xs-6
			= link_to 'Back', root_path
	.row
		.col-md-6.col-sm-6.col-xs-6
			= search_form_for @q do |f|
				= f.search_field :name_cont, placeholder: 'Enter Name'
				= f.submit 'Search', :class => 'btn btn-primary spaced-button'

.container
	table.table
		thead
			tr
				th = sort_link(@q, :name)
				th = sort_link(@q, :date)
				th = sort_link(@q, :number)
				th scope='col' Description
		tbody
			- @users.each do |user|
				tr
					th scope='row' 
						=user.name
					td 
						= user.date
					td 
						= user.number
					td 
						= user.description